name: donald
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - nibabel
  - python-dotenv
  - tqdm
  - rich
  - pyqtgraph  
  - pip:
      - mrsitoolbox
      - PyQt6
      - PyQt6-Qt6
      - PyQt6-sip
      - bctpy
      - neuroCombat
