name: donald
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - nibabel
  - python-dotenv
  - tqdm
  - rich
  - pyqtgraph   # optional plotting helper used in some tools
  - pip:
      - mrsitoolbox==1.0.11
      - PyQt6
      - PyQt6-Qt6
      - PyQt6-sip
